/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const HYPERCUBE_PROJECTION_ROTATION_SPEED: typeof import('./composables/useHypercube').HYPERCUBE_PROJECTION_ROTATION_SPEED
  const MOBIUS_ROTATION_SPEED: typeof import('./composables/useMobiusStrip').MOBIUS_ROTATION_SPEED
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const generateHypercubeData: typeof import('./composables/useHypercube').generateHypercubeData
  const generateHypercubeSurfaceIndices: typeof import('./composables/useHypercube').generateHypercubeSurfaceIndices
  const generateMobiusData: typeof import('./composables/useMobiusStrip').generateMobiusData
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const isTransitioning: typeof import('./composables/useRouteTransitionOrchestrator').isTransitioning
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const playRouteTransition: typeof import('./composables/useRouteTransitionOrchestrator').playRouteTransition
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const stepAuthorSlideIndex: typeof import('./composables/useAuthorSlider').stepAuthorSlideIndex
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useArticleReading: typeof import('./composables/useArticleReading').useArticleReading
  const useAttrs: typeof import('vue').useAttrs
  const useAuthorSlider: typeof import('./composables/useAuthorSlider').useAuthorSlider
  const useBlogQueryState: typeof import('./composables/useBlogQueryState').useBlogQueryState
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useHomePanels: typeof import('./composables/useHomePanels').useHomePanels
  const useHypercube: typeof import('./composables/useHypercube').useHypercube
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMatterCapsules: typeof import('./composables/useMatterCapsules').useMatterCapsules
  const useMobiusStrip: typeof import('./composables/useMobiusStrip').useMobiusStrip
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSiteStore: typeof import('./stores/site').useSiteStore
  const useSlots: typeof import('vue').useSlots
  const useStarField: typeof import('./composables/useStarField').useStarField
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTheme: typeof import('./composables/useTheme').useTheme
  const useThreeScene: typeof import('./composables/useThreeScene').useThreeScene
  const useVisitorCount: typeof import('./composables/useVisitorCount').useVisitorCount
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { HypercubeData, Hypercube } from './composables/useHypercube'
  import('./composables/useHypercube')
  // @ts-ignore
  export type { MobiusDataParams, MobiusData, MobiusStrip } from './composables/useMobiusStrip'
  import('./composables/useMobiusStrip')
  // @ts-ignore
  export type { StarField } from './composables/useStarField'
  import('./composables/useStarField')
  // @ts-ignore
  export type { ThemeMode } from './composables/useTheme'
  import('./composables/useTheme')
  // @ts-ignore
  export type { ThreeSceneOptions, ThreeScene } from './composables/useThreeScene'
  import('./composables/useThreeScene')
  // @ts-ignore
  export type { SiteMode, SitePanelMode, WorksViewMode } from './stores/site'
  import('./stores/site')
}
