/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./components/article/ArticleContent.vue')['default']
    ArticleHero: typeof import('./components/article/ArticleHero.vue')['default']
    ArticleProse: typeof import('./components/article/ArticleProse.vue')['default']
    ArticleToc: typeof import('./components/article/ArticleToc.vue')['default']
    AuthorAboutScreen: typeof import('./components/home/author/AuthorAboutScreen.vue')['default']
    AuthorCapsuleScreen: typeof import('./components/home/author/AuthorCapsuleScreen.vue')['default']
    AuthorContactLinks: typeof import('./components/home/author/AuthorContactLinks.vue')['default']
    AuthorHeroScreen: typeof import('./components/home/author/AuthorHeroScreen.vue')['default']
    AuthorPanel: typeof import('./components/home/AuthorPanel.vue')['default']
    AuthorPoemScreen: typeof import('./components/home/author/AuthorPoemScreen.vue')['default']
    BlogFilterRail: typeof import('./components/home/blog/BlogFilterRail.vue')['default']
    BlogResultCard: typeof import('./components/home/blog/BlogResultCard.vue')['default']
    BlogResults: typeof import('./components/home/blog/BlogResults.vue')['default']
    BlogSearchBar: typeof import('./components/home/blog/BlogSearchBar.vue')['default']
    FriendLinkApplicationForm: typeof import('./components/home/friend/FriendLinkApplicationForm.vue')['default']
    FriendLinkCard: typeof import('./components/home/friend/FriendLinkCard.vue')['default']
    FriendLinkGrid: typeof import('./components/home/friend/FriendLinkGrid.vue')['default']
    FriendPanel: typeof import('./components/home/FriendPanel.vue')['default']
    PostPanel: typeof import('./components/home/PostPanel.vue')['default']
    ReadingOverlay: typeof import('./components/home/ReadingOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTransitionShell: typeof import('./components/layout/RouteTransitionShell.vue')['default']
    SiteNav: typeof import('./components/layout/SiteNav.vue')['default']
    SlideController: typeof import('./components/home/SlideController.vue')['default']
    ThemeToggle: typeof import('./components/layout/ThemeToggle.vue')['default']
    ThreeSceneCanvas: typeof import('./components/scene/ThreeSceneCanvas.vue')['default']
    VisitorCountBadge: typeof import('./components/home/VisitorCountBadge.vue')['default']
    WorkActionLinks: typeof import('./components/home/works/WorkActionLinks.vue')['default']
    WorksCaseView: typeof import('./components/home/works/WorksCaseView.vue')['default']
    WorksPanel: typeof import('./components/home/WorksPanel.vue')['default']
    WorksViewToggle: typeof import('./components/home/works/WorksViewToggle.vue')['default']
  }
}
